[theme]
primaryColor = "#10a37f"
backgroundColor = "#343541"
secondaryBackgroundColor = "#202123"
textColor = "#ececf1"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

